module.exports = [ 
    "Beverly Hotel Beirut",
    "The Parisian Hotel",
    "Gefinor Rotana",
    "Lahoya Homes",
    "NY Suites",
    "Lancaster Tamar Hotel",
    "Lavender Home Hotel",
    "Ramada by Windham Downtown",
    "Arthaus Beirut ",
    "Elite Hotel & SPA", //10
    "La Siesta Hotel & Beach Resort",
    "Raouche Arjaan by Rotana",
    "Maximus Hotel Byblos",
    "Le Pave Residences",
    "Marble Tower",
    "Lancaster Eden Bay",
    "Sofitel Beirut Le Gabriel",           
    "Intercontinental Phoenicia Beirut",
    "Xpress by Smallville",
    "Staybridge Suites Beirut",//20
    "Mateus Hotel",
    "Kempinski Summerland Hotel & Resort Beirut",
    "Zur Studios And Suites",
    "Studio 44",
    "Vu'z Hotel",
    "Hotello Guest Suites",
    "The Rooms Boutique Hotel",
    "Crowne Plaza Beirut",            
    "Hotel Wakim",
    "Monte Cassino Boutique Hotel",//30
    "Dar Camelia",
    "Heaven Prestige Hotel",
    "Intercontinental Hotels Mzaar(Mountain Resort & Spa)",
    "Monteverde Hotel",
    "Madisson Hotel",
    "Ibiza Hotel",
    "Lost",
    "Jiyeh Marina Resort Hotel & Chalets",
    "Q Hotel",
    "Bay Lodge Boutique Hotel",//40
    "41 Twelve",
    "Hollywood Inn Boutique Hotel",
    "Louis V Hotel Beirut",
    "The Lodge Inn Hotel",
    "Hamra Urban Gardens",
    "Burj On Bay Hotel",
    "Rb 466 Hotel",
    "Liqaa Hotel",
    "Sky Suites",
    "Le Royal Hotel Beirut", //50
    "Portaluna Hotel & Resort",
    "Berdawny Apartments",
    "Le Six Hotel And Resort",
    "King Suites Hotel",
    "Dar Alice",
    "Bkerzay",
    "Miramar Hotel Resort And Spa",
    "La Place Hotel",
    "La Maison des Cèdres",
    "Faraya Village Club",//60
    "Royal Tulip Achrafieh",
    "Aleph Boutique Hotel",
    "Nine Seven Hotel",
    "Brazilia Suites Hotel",
    "Aley Suites",
    "Batroun Bahsa Bay",
    "Suite Hotel Merlot",
    "Batroun boutique suites",
    "Lahoya Garden",
    "Universal Residence",//70
    "Villetta di Faraya",
    "Urban Faqra Hotel",
    "Three O Nine Hotel",
    "Platinum Hotel",
    "Sunrise Hotel",
    "MzaarViews Chalets",
    "Albergo Hotel",
    "Massabki Hotel",   
    "Jounieh Suites Boutique Hotel",       
    "Radisson Blu Martinez Hotel Beirut",//80
    "Ramada Plaza Beirut-Raouche",
    "Four Points by Sheraton Le Verdun",
    "City Suite Hotel",
    "Lamedina Hotel & Resort",
    "Hilton Beirut Metropolitan Palace",
    "Garden Hotel",
    "1866 Court & Suites Hotel",
    "Crown Royal Hotel Tyr",
    "O Monot Boutique Hotel Beirut",
    "Hilton Beirut Habtoor Grand",//90
    "Hotel Ehden",
    "Radisson Blu Hotel Beirut Verdun",
    "St Paul Resort",
    "Parktower Suites",
    "Azur Suites Hotel & Apartments",
    "Lancaster Plaza Beirut",
    "Duroy Hotel",
    "Theodos Lodge Hotel By Hansa",
    "Casa D'or Hotel",
    "Plaza Hotel",//100
    "Markazia Suites",
    "Hotel Cavalier",
    "Riviera Hotel Beirut",
    "Mayflower Hotel",
    "The Smallville Hotel",
    "Byblostar Hotel",
    "Coral Beach Hotel and Resort Beirut",
    "The Ray Hotel and Studios",
    "Lancaster Hotel Raouche",
    "WH Hotel",//110
    "Sodeco Suites",
    "Warwick Palm Beach Hotel",
    "Serenada Golden Palace - Boutique Hotel",
    "Hotel Napoleon Beirut",
    "El Sheikh Suites Hotel",
    "Bliss 3000 Furnished Studios",
    "Lahoya Verdun",
    "The J Hotel & Spa",
    "La Vida Suite",
    "Al Murjan Palace Hotel",//120
    "Verdun Suites Hotel",
    "Cedars Palace",
    "Imperial Suites Hotel",
    "Blue Jay Valley",
    "Urban Central Suites",
    "Holiday Home Suites",
    "Le Grand Chalet Zaarour",
    "Hotel L'Aiglon",
    "Mountain View Cedars",
    "Zett hotel",//130
    "Grand Kadri Hotel",
    "Caesar's Park Hotel",
    "The Key Beirut",
    "Lancaster Suites Raouche",
    "L'Auberge de la Mer",
    "Nest 1 Hotel",
    "Hotel 35 Rooms",
    "Grand Gabriel",
    "The Gem Boutique Hotel",
    "Suite Hotel Chrome",//140
    "Batroun loft guest house",
    "Citea Apart-Hotel",
    "Bel Azur Hotel",
    "Stone Cellars",
    "Gems Hotel", 
    "Bossa Nova Beirut Hotel",
    "Warwick Stone 55 Hotel",
    "Movenpick Hotel Beirut",
    "Majestic Byblos Grand Hotel",
    "Orient Queen Homes Hotel",//150
    "Grand Suites Hotel",
    "Via Verde Hotel",
    "Le Commodore Hotel",
    "Orient Prince Hotel",
    "Chalet de Charme",
    "Regency Palace Hotel",
    "Bayview Hotel Beirut",
    "Reston Hotel",
    "Charles Hotel",
    "Offwhite",//160
    "Beit Wadih",
    "Princessa Hotel",
    "Palm Ville Suites",
    "Kanaan Group Hotel",
    "Monot Suites",
    "Cosmopolitan Hotel",
    "Queens Land Hotel",
    "Hotel Al Bustan",
    "Elegant Suites Beirut",
    "Golden Lili Resort & Spa",//170
    "Votre Hotel",
    "Hotel De Ville",
    "Midtown Hotel & Suites",
    "Stone Chalets",
    "Vista Del Mar Hotel",
    "Mozart Hotel",
    "Queens Suite Hotel",
    "Caramel Boutique Hotel",
    "Delora Hotel and Suites",
    "B Residence",//180
    "Printania Palace Hotel",
    "Padova Hotel",
    "Regis Hotel",
    "La Tourelle",
    "Four Seasons Halat",
    "Alaamira Furnished Apartments",
    "Holiday Suites Hotel & Beach Resort",
    "Bauhaus Chalets Apartment",
    "The Stay Furnished Apartments",
    "Odom Retreat",//190
    "Hotel Chbat",
    "Royal Garden Hotel",
    "Kantari Suites",
    "Old Town Guesthouses",
    "Remhala Guest House",
    "Saifi Suites",
    "Suiteness Deir el qamar",
    "Sea Valley Suites",
    "Pearl of Beirut Hotel & Spa",
    "Divan Hotel Apartments",//200
    "Monte Mare Hotel",
    "Luxor Hotel",
    "Hotel Monte bello",
    "Castel Mare Beach Hotel & Resort",
    "Grand Concerto Hotel",
    "Byblos Sur Mer",
    "El Boutique Hotel",
    "Halat sailing club Guest house",
    "Siena Hotel",
    "Hayali Suites",//210
    "Eden Hotel",
    "Byblos Guest House",
    "Via Mina Hotel",
    "Le Tournant Hotel & Resort",
    "Legend Hotel", 
    "The Grand Meshmosh Hotel",
    "Hotel Xperience",
    "Dolls Hotel By Eurostars",
    "Villa Queens",
    "Koura Nahla Apartment",//220
    "Zoukotel Hotel",
    "Beit El Bahr",
    "Auberge Braidy",
    "Promenade Hotel",
    "Adma Blue Screen",
    "Victory Byblos Hotel & Spa",
    "Valley View Hotel ",
    "Le Blanc Bleu",
    "White House Suites",
    "Tyre Boutique Apartments",//230
    "Monoberge Hotel",
    "Camelot Hotel",
    "Eleven Hotel",
    "Dynasty Suite",
    "Austria Luxury Apartments",
    "Bella Rosa Hotel",
    "Iris Flower Hotel",
    "Whitelace Resort",
    "Mist Hotel & Spa",
    "Green Lake Hotel Jezzine",//240
    "Olive Gardens Resort",
    "Reef Zefta Hotel",
    "Ricky's Guest house",
    "Byblos Comfort Hotel",
    "Vanda Hotel & Spa", 
    "Layali Al Shams Hotel",
    "One To One Hotel",
    "Damour Country Club",
    "Oakridge Hotel & Spa",
    "Marbella Hotel",//250
    "Cimer Saframarine Beach Resort",
    "Hotel St Jean",
    "Guias Boutique Hotel & Spa",
    "Lahoya Suites",
    "The Residence 649",
    "Ehden Village Residences",
    "Mon Refuge Auberge",
    "Faqra Palace",
    "Damask Rose Lebanese Guest House",
    "City Suite Aley",//260
    "Faraya Village Club",
    "Mresty Guest House",
    "Domaine des Oliviers",
    "El Achkar Guesthouse",
    "Aquarius Touristic Resort",
    "Batroun Van camping",
    "Al Arja Apartment",
    "La Maison des Sources",
    "The Perfect Getaway",
    "Beit El Deif",//270
    "Raj Hotel",
    "Sequoia Guesthouse",
    "La Reserve Faraya",
    "Grand Hotel Beirut",
    "Grand hôtel Bois de Boulogne",
    "Lamunia Hotel"
  
]